# version: '3'

# services:
  
#   db:
#     image: postgres:latest
#     networks:
#       - pwc-network
#     environment:
#       - POSTGRES_DB=sonar
#       - POSTGRES_USER=sonar
#       - POSTGRES_PASSWORD=sonar

#   sonarqube:
#       image: sonarqube:latest
#       ports:
#         - "9000:9000"
#       networks:
#         - pwc-network
#       environment:
#         - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
#         - SONARQUBE_JDBC_USERNAME=sonar
#         - SONARQUBE_JDBC_PASSWORD=sonar
      
#       depends_on:
#         - db


# networks:
#   pwc-network:
#     driver: bridge


version: '3'

services:
  db:
    image: postgres:latest
    networks:
      - pwc-network
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

  sonarqube:
    build: .
    ports:
      - "9000:9000"
    networks:
      - pwc-network
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    depends_on:
      - db

networks:
  pwc-network:
    driver: bridge
