---
- name: Install and configure Apache on Ubuntu
  hosts: web-servers
  become: yes  # Use sudo

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Set Apache to listen on port 5000
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen\s+80$'
        line: 'Listen 5000'
      notify:
        - restart apache

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes  # Start Apache on boot

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
