---
- name: Configure Nginx for SonarQube and Apache
  hosts: web-servers
  become: yes
  tasks:
    - name: Create Nginx site configuration
      template:
        src: reverse-proxy.conf.j2
        dest: /etc/nginx/sites-available/reverse-proxy.conf

    - name: Enable the Nginx site configuration
      file:
        src: /etc/nginx/sites-available/reverse-proxy.conf
        dest: /etc/nginx/sites-enabled/reverse-proxy.conf
        state: link

    - name: Remove the default Nginx site configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      ignore_errors: yes

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test
      ignore_errors: yes

    - name: Fail if Nginx configuration test failed
      fail:
        msg: "Nginx configuration test failed"
      when: nginx_test.rc != 0

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
